-- The application should have one user role - PUBLISHER.
INSERT INTO `role` VALUES (1, 'PUBLISHER');
-- Resource to authenticate a particular user. Users may be hardcoded.
INSERT INTO `user` (user_id, email, last_name, name, password) VALUES
  (1, 'root', 'Long', 'Andy', '$2a$10$gq4uceqA/Y43PVPgTDMXJesbnAVPX67JsrrCNSIYTHxt2yY5YETCu'),
  (2, 'user', 'Cooper', 'Chandler', '$2a$10$/4plgdI4oGTYvaHYttJ5hurEJvkWMPq5l.7firtJmP3nz./AQRqP2');
-- relationship users and roles
INSERT INTO `user_role` VALUES (1, 1), (2, 1);
-- add test blog posts
INSERT INTO `post` (post_id, user_id, create_date, post_title, post_body, photo_file_name) VALUES
  (1, 1, parsedatetime('17-09-2017 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),
    'Pagedraw UI Builder Turns Your Website Design Mockup Into Code Automatically',
    '<h3>Lorem Ipsum: when, and when not to use it</h3><p>Do you like Cheese Whiz? Spray tan? Fake eyelashes? That''s what is Lorem Ipsum to many—it rubs them the wrong way, all the way. It''s unreal, uncanny, makes you wonder if something is wrong, it seems to seek your attention for all the wrong reasons. Usually, we prefer the real thing, wine without sulfur based preservatives, real butter, not margarine, and so we''d like our layouts and designs to be filled with real words, with thoughts that count, information that has value. </p><p>The toppings you may chose for that TV dinner pizza slice when you forgot to shop for foods, the paint you may slap on your face to impress the new boss is your business. But what about your daily bread? Design comps, layouts, wireframes—will your clients accept that you go about things the facile way? Authorities in our business will tell in no uncertain terms that Lorem Ipsum is that huge, huge no no to forswear forever. Not so fast, I''d say, there are some redeeming factors in favor of greeking text, as its use is merely the symptom of a worse problem to take into consideration.</p>',
    'post-1.jpg'),
    (2, 1, parsedatetime('15-09-2017 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),
    'Chrome Extension Protects Against JavaScript-Based CPU Side-Channel Attacks',
    '<h3>Lorem Ipsum: when, and when not to use it</h3><p>Do you like Cheese Whiz? Spray tan? Fake eyelashes? That''s what is Lorem Ipsum to many—it rubs them the wrong way, all the way. It''s unreal, uncanny, makes you wonder if something is wrong, it seems to seek your attention for all the wrong reasons. Usually, we prefer the real thing, wine without sulfur based preservatives, real butter, not margarine, and so we''d like our layouts and designs to be filled with real words, with thoughts that count, information that has value. </p><p>The toppings you may chose for that TV dinner pizza slice when you forgot to shop for foods, the paint you may slap on your face to impress the new boss is your business. But what about your daily bread? Design comps, layouts, wireframes—will your clients accept that you go about things the facile way? Authorities in our business will tell in no uncertain terms that Lorem Ipsum is that huge, huge no no to forswear forever. Not so fast, I''d say, there are some redeeming factors in favor of greeking text, as its use is merely the symptom of a worse problem to take into consideration.</p>',
    'post-2.jpg'),
    (3, 2, parsedatetime('17-05-2016 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),
    'Ask HN: Does Anybody Still Use JQuery?',
    '<h3>Lorem Ipsum: when, and when not to use it</h3><p>Do you like Cheese Whiz? Spray tan? Fake eyelashes? That''s what is Lorem Ipsum to many—it rubs them the wrong way, all the way. It''s unreal, uncanny, makes you wonder if something is wrong, it seems to seek your attention for all the wrong reasons. Usually, we prefer the real thing, wine without sulfur based preservatives, real butter, not margarine, and so we''d like our layouts and designs to be filled with real words, with thoughts that count, information that has value. </p><p>The toppings you may chose for that TV dinner pizza slice when you forgot to shop for foods, the paint you may slap on your face to impress the new boss is your business. But what about your daily bread? Design comps, layouts, wireframes—will your clients accept that you go about things the facile way? Authorities in our business will tell in no uncertain terms that Lorem Ipsum is that huge, huge no no to forswear forever. Not so fast, I''d say, there are some redeeming factors in favor of greeking text, as its use is merely the symptom of a worse problem to take into consideration.</p>',
    'post-3.jpg'),
    (4, 2, parsedatetime('27-07-2016 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),
    'Why Node.js Is The Coolest Kid On The Backend Development Block!',
    '<h3>Lorem Ipsum: when, and when not to use it</h3><p>Do you like Cheese Whiz? Spray tan? Fake eyelashes? That''s what is Lorem Ipsum to many—it rubs them the wrong way, all the way. It''s unreal, uncanny, makes you wonder if something is wrong, it seems to seek your attention for all the wrong reasons. Usually, we prefer the real thing, wine without sulfur based preservatives, real butter, not margarine, and so we''d like our layouts and designs to be filled with real words, with thoughts that count, information that has value. </p><p>The toppings you may chose for that TV dinner pizza slice when you forgot to shop for foods, the paint you may slap on your face to impress the new boss is your business. But what about your daily bread? Design comps, layouts, wireframes—will your clients accept that you go about things the facile way? Authorities in our business will tell in no uncertain terms that Lorem Ipsum is that huge, huge no no to forswear forever. Not so fast, I''d say, there are some redeeming factors in favor of greeking text, as its use is merely the symptom of a worse problem to take into consideration.</p>',
    'post-4.jpg'),
    (5, 2, parsedatetime('11-07-2018 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),
    'CSS Float: A Tutorial',
    '<h3>Lorem Ipsum: when, and when not to use it</h3><p>Do you like Cheese Whiz? Spray tan? Fake eyelashes? That''s what is Lorem Ipsum to many—it rubs them the wrong way, all the way. It''s unreal, uncanny, makes you wonder if something is wrong, it seems to seek your attention for all the wrong reasons. Usually, we prefer the real thing, wine without sulfur based preservatives, real butter, not margarine, and so we''d like our layouts and designs to be filled with real words, with thoughts that count, information that has value. </p><p>The toppings you may chose for that TV dinner pizza slice when you forgot to shop for foods, the paint you may slap on your face to impress the new boss is your business. But what about your daily bread? Design comps, layouts, wireframes—will your clients accept that you go about things the facile way? Authorities in our business will tell in no uncertain terms that Lorem Ipsum is that huge, huge no no to forswear forever. Not so fast, I''d say, there are some redeeming factors in favor of greeking text, as its use is merely the symptom of a worse problem to take into consideration.</p>',
    'post-5.jpg'),
    (6, 1, parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),
    'Tell-A-Tool: Guide To Web Design And Development Tools',
    '<h3>Lorem Ipsum: when, and when not to use it</h3><p>Do you like Cheese Whiz? Spray tan? Fake eyelashes? That''s what is Lorem Ipsum to many—it rubs them the wrong way, all the way. It''s unreal, uncanny, makes you wonder if something is wrong, it seems to seek your attention for all the wrong reasons. Usually, we prefer the real thing, wine without sulfur based preservatives, real butter, not margarine, and so we''d like our layouts and designs to be filled with real words, with thoughts that count, information that has value. </p><p>The toppings you may chose for that TV dinner pizza slice when you forgot to shop for foods, the paint you may slap on your face to impress the new boss is your business. But what about your daily bread? Design comps, layouts, wireframes—will your clients accept that you go about things the facile way? Authorities in our business will tell in no uncertain terms that Lorem Ipsum is that huge, huge no no to forswear forever. Not so fast, I''d say, there are some redeeming factors in favor of greeking text, as its use is merely the symptom of a worse problem to take into consideration.</p>',
    'post-6.jpg');
